const express =require('express')
const Router=express.Router()
const multer=require("../middleware/multer")
// const upload=require("../middleware/multer")
// const pdfController=require("../controllers/file")
const authController=require("../controllers/user")
const productController=require("../controllers/productController")
const authenticated=require("../middleware/authentication")

// const authenticated=require("../middleware/authenticationChecker")

Router.post("/signup",authController.creatUser)
Router.post("/login",authController.userLogin)
Router.post("/category",authController.addCategory)
Router.post("/sub-category",authenticated.verify,authController.addSubCategory)
Router.get("/get-category",authenticated.verify,authController.getCategory)
Router.get("/get-subcategory",authenticated.verify,authController.getSubCategory)
Router.get("/get-product",authenticated.verify,authController.getProduct)
Router.post("/product",multer.array("file",3),productController.addProduct)
Router.post("/search",authenticated.verify,authController.Search)
Router.post("/edit-product",authenticated.verify,productController.updateProduct)
Router.post("/single-product",authenticated.verify,productController.singleProduct)
Router.post("/whishlist",authenticated.verify,productController.whsihList)
Router.post("/filter",authenticated.verify,productController.filterProducts)
Router.post("/get-whishlist",authenticated.verify,productController.getWhishlist)
Router.post('/refresh',authController.generateAcessToken)

module.exports=Router